### ISSUE TITLE
Get rid of bintray

### ISSUE THREAD

**Issue by holgerbrandl** [GuiaBolso/fixed-length-file-handler#19]
Since bintray is being retired, I'm wondering of this great library will be hosted elsewhere? Sticking to bintray will break compilation starting in May, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by LeoColman** [comment]
Library is now available at Maven Central!

**Comment by holgerbrandl** [comment]
Awesome thanks!
